In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr , arr.dtype)

arr1 = np.array([1,2,3.12,4,5,6])
print(arr1 , arr1.dtype)

arr2 = np.array([1,2,3.12,4,5,6,"prime"])
print(arr2 , arr2.dtype)

[1 2 3 4 5 6] int64
[1.   2.   3.12 4.   5.   6.  ] float64
['1' '2' '3.12' '4' '5' '6' 'prime'] <U32


In [8]:
arr1 = np.array([5 + 7j])
arr2 = np.array([3 + 5j])
print(arr1 , arr1.dtype)
print(arr2, arr2.dtype)
print(arr1 + arr2)
print(arr1 - arr2)

[5.+7.j] complex128
[3.+5.j] complex128
[8.+12.j]
[2.+2.j]


In [9]:
arr = np.array(["prime" , {1,2,3}, 3.14])
print(arr , arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [18]:
# multi_dimentional_array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_colums = np.sum(arr2D , axis = 0)
print(sum_of_colums)
sum_of_rows = np.sum(arr2D , axis = 1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]
