In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])
print(arr ,type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [5]:
#create numpy array

In [8]:
arr1 = np.array([1,5,4,6,2,14])
print(arr1 , len(arr1) , type(arr1))

arr2 = np.array([1,5,4,6,2,14,"prime"])
print(arr2 , arr2.dtype)

[ 1  5  4  6  2 14] 6 <class 'numpy.ndarray'>
['1' '5' '4' '6' '2' '14' 'prime'] <U21


In [9]:
# 2D array

In [15]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D , arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [16]:
#zeros array

In [22]:
arr3 = np.zeros((2,3), dtype="int64")
print(arr3 , arr3.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [23]:
#ones array

In [28]:
arr4 = np.ones((3), dtype = "int64")
print(arr4)

[1 1 1]


In [29]:
#prefill with val

In [30]:
arr4 = np.full((3,3),100)
print(arr4)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [31]:
#identity mtx

In [33]:
arr = np.eye((3))
print(arr , arr.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [38]:
#range
arr = np.arange(1 , 10 , 2)
print(arr)

[1 3 5 7 9]


In [42]:
#linspace

arr = np.linspace(1 ,100 , 4)
print(arr , arr.shape)

[  1.  34.  67. 100.] (4,)


In [11]:
#vectorization

arr = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,4,1,5,6,])
print(arr **2)
print(arr +10)
print(arr + arr2)

[ 1  4  9 16 25 36]
[11 12 13 14 15 16]
[ 2  4  7  5 10 12]


In [14]:
#normalize

arr = np.array([[1,2],[3,4]])
mean =(arr.mean())
std =  (arr.std())

normalize_arr = (arr- mean)/std
print(normalize_arr)



[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [25]:
#methametical functions

arr = np.array([1,2,3,4,5,])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [28]:
#power fxn

arr = np.array([1,2,3,4,5,])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
