In [10]:
#reshape 
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)

reshape = arr.reshape((3,2))
print(reshape ,reshape.shape)

#2d => 1d

flatended = arr.flatten()
print(flatended , flatended.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [12]:
#indexing

arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[2])
print(arr[5])

1
3
6


In [14]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1][1])
print(arr[0][0])

5
1


In [15]:
#fancy indexing

arr = np.array([1,2,3,4,5,6])

idx = [0,2,5]
print(arr[idx])

[1 3 6]


In [18]:
#boolean indexing

arr = np.array([1,2,3,4,5,6])
print(arr[arr % 2 ==0 ])
print(arr[arr < 2])

[2 4 6]
[1]


In [23]:
#slicing

arr = np.array([1,2,3,4,5,6])
print(arr[1:2])
print(arr[1:5])
print(arr[1:])
print(arr[:5])
print(arr[::3])

[2]
[2 3 4 5]
[2 3 4 5 6]
[1 2 3 4 5]
[1 4]
